sonar.projectKey=JakeRoxs_dsos_9178fbff-b3bf-4c2c-9c34-efc7eb852932
sonar.projectName=dsos
sonar.sources=.
sonar.exclusions=**/*.java, Resources/**/*, Source/ThirdParty/**, build/**
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.sourceEncoding=UTF-8