<Project>
  <PropertyGroup>
    <RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..'))</RepoRoot>
    <BaseIntermediateOutputPath>$(RepoRoot)/intermediate/dotnet/$(OS)/$(MSBuildProjectName)/$(Platform)/$(Configuration)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(RepoRoot)/bin/managed/$(OS)/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
